[package]
name = "quantizer-aux2"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
# aviutl2 = "0.18.0"
aviutl2 = { git = "https://github.com/sevenc-nanashi/aviutl2-rs.git" }
aviutl2-eframe = { git = "https://github.com/sevenc-nanashi/aviutl2-rs.git" }
